# Generated by Django 6.0 on 2025-12-08 23:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaTeXTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='اسم القالب')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='الرابط')),
                ('category', models.CharField(choices=[('classic', 'كلاسيكي'), ('professional', 'احترافي'), ('creative', 'إبداعي'), ('graduate', 'خريجين')], max_length=50, verbose_name='الفئة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('latex_file_name', models.CharField(help_text='مثال: classic_arabic_v1.tex', max_length=200)),
                ('schema_class_name', models.CharField(help_text='مثال: ClassicArabicCVSchema', max_length=100)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='template_previews/', verbose_name='صورة المعاينة')),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=500)),
                ('usage_count', models.IntegerField(default=0, verbose_name='عدد الاستخدامات')),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='التقييم')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'قالب LaTeX',
                'verbose_name_plural': 'قوالب LaTeX',
                'ordering': ['-usage_count', '-rating'],
            },
        ),
    ]
