# Generated by Django 6.0 on 2025-12-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_latextemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='latextemplate',
            options={'ordering': ['-usage_count', '-rating'], 'verbose_name': 'LaTeX templates', 'verbose_name_plural': 'LaTeX templates'},
        ),
        migrations.AddField(
            model_name='compilejob',
            name='cv_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
