# Generated by Django 6.0 on 2025-12-20 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_latextemplate_options_compilejob_cv_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compilejob',
            options={'ordering': ['-created_at'], 'verbose_name': 'Compile Job', 'verbose_name_plural': 'Compile Jobs'},
        ),
        migrations.AddField(
            model_name='compilejob',
            name='celery_task_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='compilejob',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compilejob',
            name='duration_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compilejob',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='compilejob',
            name='pdf_size_bytes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compilejob',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='compilejob',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compilejob',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='compilejob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='compilejob',
            name='logs',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='compilejob',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compile_jobs', to='core.project'),
        ),
        migrations.AlterField(
            model_name='compilejob',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='QUEUED', max_length=20),
        ),
        migrations.AlterField(
            model_name='compilejob',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compile_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='compilejob',
            index=models.Index(fields=['status', '-created_at'], name='job_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='compilejob',
            index=models.Index(fields=['triggered_by', '-created_at'], name='job_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='compilejob',
            index=models.Index(fields=['project', '-created_at'], name='job_project_date_idx'),
        ),
        migrations.AddIndex(
            model_name='compilejob',
            index=models.Index(condition=models.Q(('status', 'SUCCESS')), fields=['-created_at'], name='job_recent_success_idx'),
        ),
    ]
