# Generated by Django 6.0 on 2025-12-20 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_compilejob_options_compilejob_celery_task_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='latextemplate',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
